### ISSUE TITLE
Error in launch python

### ISSUE THREAD

**Issue by eldarius** [BrettMayson/Arma3Server#28]
root@Eldarius:/home/Arma3Server# python3 launch.py 
Traceback (most recent call last):
  File "launch.py", line 12, in <module>
    CONFIG_FILE = os.environ["ARMA_CONFIG"]
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'ARMA_CONFIG'

**Comment by BrettMayson** [comment]
Running the scripts directly is not supported, you need to use it via Docker
