### ISSUE TITLE
Cannot find mods html

### ISSUE THREAD

**Issue by Trikpatknd** [BrettMayson/Arma3Server#80]
Docker compose
`version: '3.8'
services:
  arma3:
    build: .
    image: ghcr.io/brettmayson/arma3server/arma3server:latest
    platform: linux/amd64
    container_name: arma3
    ports:
      - 2302-2306/udp
    volumes:
      - './missions:/arma3/mpmissions'
      - './configs:/arma3/configs'
      - './mods:/arma3/mods'
      - './servermods:/arma3/servermods'
    env_file: .env
    restart: unless-stopped
`
env file
` ARMA_BINARY=./arma3server_x64
ARMA_CDLC=
ARMA_CONFIG=main.cfg
ARMA_LIMITFPS=144
ARMA_PARAMS=
ARMA_PROFILE=main
ARMA_WORLD=empty
HEADLESS_CLIENTS=0
HEADLESS_CLIENTS_PROFILE="$profile-hc-$i" # valid placeholders: $profile, $i, $ii
MODS_LOCAL=true
MODS_PRESET="/arma3/steamapps/workshop/content/107410/aup.html"
PORT=2302
STEAM_BRANCH=public
STEAM_BRANCH_PASSWORD=
STEAM_PASSWORD=***
STEAM_USER=***`

console output is:

> antistasi-server  | Traceback (most recent call last):
antistasi-server  |   File "/launch.py", line 66, in <module>
antistasi-server  |     mods.extend(workshop.preset(os.environ["MODS_PRESET"]))
antistasi-server  |   File "/workshop.py", line 34, in preset
antistasi-server  |     with open(mod_file) as f:
antistasi-server  | FileNotFoundError: [Errno 2] No such file or directory: '/arma3/steamapps/workshop/content/107410/aup.html'

**Comment by BrettMayson** [comment]
I would recommend putting your html file in configs, please checkout the new v2 version for an easier setup
